/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";

import PropTypes from "prop-types";

const HashtagFilled = props => {
  const { size, color, bgColor, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M21 7V17C21 19.209 19.209 21 17 21H7C4.791 21 3 19.209 3 17V7C3 4.791 4.791 3 7 3H17C19.209 3 21 4.791 21 7Z"
        fill={bgColor}
        stroke={bgColor}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M10 8V16"
        stroke={color}
        strokeWidth="1.389"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M14 8V16"
        stroke={color}
        strokeWidth="1.389"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8 14H16"
        stroke={color}
        strokeWidth="1.389"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8 10H16"
        stroke={color}
        strokeWidth="1.389"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};

HashtagFilled.defaultProps = {
  color: "white",
  bgColor: "#68737D",
  size: 24,
};

HashtagFilled.propTypes = {
  color: PropTypes.string,
  bgColor: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};

export { HashtagFilled };
