export const EDITOR_CONTENT_CLASSNAME = "scooter-editor-content";

export const EDITOR_PADDING_SIZE = 12;

export const EDITOR_BORDER_SIZE = 1;

export const EDITOR_LINE_HEIGHT = 21;

export const UNSPLASH_BASE_URL = "https://api.unsplash.com/search/photos";

export const IFRAMELY_BASE_URL =
  "http://127.0.0.1:4455/.factly/dega/server/meta";

export const EDITOR_OPTIONS = {
  // DEFAULT EDITOR OPTIONS
  ASK_AI: "ask-ai",
  FONT_COLOR: "font-color",
  BOLD: "bold",
  ITALIC: "italic",
  UNDERLINE: "underline",
  STRIKETHROUGH: "strike",
  LINK: "link",
  PARAGRAPH: "paragraph",
  TABLE: "table",
  H1: "h1",
  H2: "h2",
  LIST_BULLETS: "bullet-list",
  LIST_ORDERED: "ordered-list",
  TEXT_ALIGN_LEFT: "text-align-left",
  TEXT_ALIGN_CENTER: "text-align-center",
  TEXT_ALIGN_RIGHT: "text-align-right",
  CODE: "code",

  // ADDON EDITOR OPTIONS
  HIGHLIGHT: "highlight",
  EMOJI: "emoji",
  CODE_BLOCK: "code-block",
  BLOCKQUOTE: "block-quote",
  IMAGE_UPLOAD: "image-upload",
  IMAGE_UPLOAD_UNSPLASH: "image-upload-unsplash",
  DIVIDER: "divider",
  VIDEO_EMBED: "video-embed",
  EMBED: "embed",
  RAW_HTML: "raw-html",

  // OTHER AVAILABLE OPTIONS
  H3: "h3",
  H4: "h4",
  H5: "h5",
  H6: "h6",
};

export const DEFAULT_EDITOR_OPTIONS = [
  EDITOR_OPTIONS.FONT_COLOR,
  EDITOR_OPTIONS.ASK_AI,
  EDITOR_OPTIONS.BOLD,
  EDITOR_OPTIONS.ITALIC,
  EDITOR_OPTIONS.UNDERLINE,
  EDITOR_OPTIONS.STRIKETHROUGH,
  EDITOR_OPTIONS.TEXT_ALIGN_LEFT,
  EDITOR_OPTIONS.TEXT_ALIGN_CENTER,
  EDITOR_OPTIONS.TEXT_ALIGN_RIGHT,
  EDITOR_OPTIONS.DIVIDER,
  EDITOR_OPTIONS.CODE,
  EDITOR_OPTIONS.CODE_BLOCK,
  EDITOR_OPTIONS.BLOCKQUOTE,
  EDITOR_OPTIONS.IMAGE_UPLOAD,
  EDITOR_OPTIONS.VIDEO_EMBED,
  EDITOR_OPTIONS.LINK,
  EDITOR_OPTIONS.PARAGRAPH,
  EDITOR_OPTIONS.TABLE,
  EDITOR_OPTIONS.H1,
  EDITOR_OPTIONS.H2,
  EDITOR_OPTIONS.H3,
  EDITOR_OPTIONS.H4,
  EDITOR_OPTIONS.H5,
  EDITOR_OPTIONS.H6,
  EDITOR_OPTIONS.LIST_BULLETS,
  EDITOR_OPTIONS.LIST_ORDERED,
  EDITOR_OPTIONS.EMBED,
  EDITOR_OPTIONS.RAW_HTML,
];
